import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { ApolloClient, InMemoryCache, gql } from '@apollo/client'

export default function Home({data}) {
  return (
    <div>
      <Head>
          <title>Star Wars Starships</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
          <main className={styles.main}>
            <h1 className={styles.title}>
              Star Wars Starships
            </h1>

            <p className={styles.description}>
              <code className={styles.code}>Learn about all the vehicles that are part of the Star Wars movie franchise.</code>
            </p>

            <div className={styles.posts}>
              {data.map(vehicle => {
                return (
                  <div 
                    key={vehicle.id}
                    className={styles.card}
                  >
                    <div style={{marginTop: '10px'}}>
                      <div>
                        <h2>
                          { vehicle.name }
                        </h2>
                        <span>Model</span>
                        <div className={styles.code}>
                          { vehicle.model }
                        </div>
                        <div className={styles.card}>
                          <div className={styles.description}>
                            <p>{`Crew Size: ${vehicle.crew}`}</p>
                            {vehicle.costInCredits && <p>Credits: {vehicle.costInCredits}</p>}
                            <p>{`Passengers: ${vehicle.passengers}`}</p>
                          </div>
                        </div>

                        <div>
                          <div>
                              { vehicle.filmConnection.films[0].title }
                            </div>
                        </div>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </main>
        
        </div>
      </div>
  )
}

export async function getStaticProps() {
  const client = new ApolloClient({
    uri: 'https://swapi-graphql.netlify.app/.netlify/functions/index',
    cache: new InMemoryCache()
  })

  const { data } = await client.query({
    query: gql`
      query QueryVehicles {
        allStarships {
          starships {
            name
            model
            filmConnection {
              films {
                title
              }
            }
            id
            costInCredits
            passengers
            crew
          }
        }
      }
    `
  })

  return {
    props: {
      data: data.allStarships.starships
    }
  }
}

